### ISSUE TITLE
Functionality and UI problems

### ISSUE THREAD

**Issue by volodymyrdovhan** [fmido88/moodle-profilefield_phone#1]
Hello,

I found few issues in your plugin functionality:

1. The UI is broken on Moodle 4.3 and the standard boost theme:
![image](https://github.com/user-attachments/assets/d1b1f774-ffb0-45d2-89d9-01041ccab597)

2. If I have 2 phone fields on the page - it does not correctly validate the second field.
As an example here - I used the same phone number and it showed me an error for the second field, but validation passed for the first one:
![image](https://github.com/user-attachments/assets/9c4f6be7-6281-4456-9273-2e7a2e124db6)
The same result if I change just one number in a phone number.
Something works wrong when few phone fields in the form.

3. When I try to update the existing field with the selected "Associate with profile field" the plugin throws a validation error. 
![image](https://github.com/user-attachments/assets/b6196e74-fe64-4e4a-8de7-7c750e4b0588)
The plugin should check if "Associate with profile field" is set for the current field.

4. I have PHP warnings after saving the user form:
![image](https://github.com/user-attachments/assets/a27585e0-b90c-4e8f-8789-424e97ea106f)
The phone code was removed in a form.

**Comment by fmido88** [comment]
2,4 should be fixed.
I'll retest 1 after the last change.
Working on 3

**Comment by fmido88** [comment]
All fixed now
