### ISSUE TITLE
Missed Privacy API implementation

### ISSUE THREAD

**Issue by volodymyrdovhan** [fmido88/moodle-profilefield_phone#4]
Hello,

your plugin is not storing any Personal data, but you still need to implement the basic Privacy class to let Moodle know about your plugin.

Please review more details here:
https://moodledev.io/general/community/plugincontribution/checklist#privacy
https://moodledev.io/docs/4.5/apis/subsystems/privacy

**Comment by fmido88** [comment]
Hello,
Privacy class added
